version: 2.1

jobs:
  test-job:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      # - setup_remote_docker:
      #     version: 20.10.23
      - run:
          name: Buildx ls
          command: |
            docker --version
            docker buildx ls

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-job
