version: 2.1

jobs:
  test-job:
    docker:
      - image: docker:stable
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
      - run:
          name: Buildx ls
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx ls

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-job
